version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      patch-and-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /tools/npm
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 1
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
